"""
generate_products.py
Generates a rich product catalog (~70 products per income×spend bucket).
Outputs data/products.csv with columns:
  product_id, name, category, income_level, spend_level, price_range

Income levels:  low = ₹1L–₹8L  ($1k–$40k)
                mid = ₹8L–₹25L  ($40k–$120k)
                high = ₹25L–₹2Cr ($120k–$240k)

Spend levels:  low / mid / high (spending score 1–100)

Run:  python generate_products.py
"""

import csv
import os

os.makedirs("data", exist_ok=True)

products = []


def add(bucket_income, bucket_spend, items):
    """items = list of (name, category, low_price, high_price)"""
    for name, category, lo, hi in items:
        products.append({
            "income_level": bucket_income,
            "spend_level": bucket_spend,
            "name": name,
            "category": category,
            "price_range": f"${lo:,}–${hi:,}",
        })


# ── LOW / LOW ─────────────────────────────────────────────────────────────────
add("low", "low", [
    ("Basic Phone Case", "accessories", 3, 6),
    ("Wired Earphones", "electronics", 5, 9),
    ("Reusable Water Bottle", "lifestyle", 6, 10),
    ("Notebook & Pen Set", "stationery", 4, 7),
    ("Plastic Lunch Box", "kitchen", 5, 9),
    ("Basic Umbrella", "lifestyle", 8, 14),
    ("Cotton Tote Bag", "fashion", 5, 9),
    ("Keychain Flashlight", "accessories", 4, 7),
    ("Simple Wall Clock", "home", 10, 18),
    ("Foldable Hand Fan", "lifestyle", 5, 8),
    ("Basic Sewing Kit", "home", 7, 12),
    ("Plastic Storage Boxes Set", "home", 10, 18),
    ("Doormat", "home", 9, 16),
    ("Basic Desk Calendar", "stationery", 4, 7),
    ("Rubber Phone Grip", "accessories", 3, 6),
    ("Budget Sunglasses", "fashion", 6, 11),
    ("Travel Toothbrush Kit", "lifestyle", 4, 8),
    ("Cotton Socks Pack (5 Pairs)", "fashion", 6, 10),
    ("Plastic Hangers Set (10)", "home", 5, 9),
    ("Mini Stapler Set", "stationery", 5, 9),
    ("Zip-Lock Bags Pack", "kitchen", 3, 6),
    ("Basic Winter Gloves", "fashion", 5, 9),
    ("Hair Ties Pack (20)", "beauty", 3, 5),
    ("Ballpoint Pens Pack (10)", "stationery", 3, 6),
    ("Plant Misting Spray Bottle", "garden", 4, 7),
    ("Sticky Notes Pack (5 Pads)", "stationery", 4, 7),
    ("Basic Dish Rack", "kitchen", 8, 14),
    ("Foldable Grocery Bag", "lifestyle", 4, 7),
    ("Shoe Insoles Pair", "fashion", 4, 7),
    ("Foam Ear Plugs Pack", "health", 3, 5),
    ("Basic Face Masks Pack", "health", 4, 7),
    ("Budget Rubber Sandals", "fashion", 5, 9),
    ("String Lights 3m", "home", 6, 11),
    ("Basic Screwdriver Set", "tools", 6, 11),
    ("Laundry Mesh Bag", "home", 4, 7),
    ("Cotton Handkerchiefs Pack (5)", "fashion", 4, 7),
    ("Compact Measuring Tape", "tools", 4, 7),
    ("Vegetable Peeler", "kitchen", 3, 6),
    ("Cable Organizer Clips (10)", "accessories", 3, 6),
    ("Budget Mouse Pad", "electronics", 4, 7),
    ("Plastic Food Containers Set", "kitchen", 8, 14),
    ("Disposable Razors Pack (8)", "health", 4, 7),
    ("Simple Alarm Clock", "home", 8, 15),
    ("Toothbrush Holder", "home", 4, 7),
    ("Shower Cap Pack", "health", 3, 5),
    ("Compact Mirror", "beauty", 3, 6),
    ("Rubber Gloves Pair", "home", 3, 6),
    ("Mini First Aid Kit", "health", 6, 11),
    ("Basic Sunscreen SPF30", "beauty", 4, 7),
    ("Clothespin Pack (20)", "home", 3, 6),
    ("Kitchen Timer", "kitchen", 5, 9),
    ("Budget Canvas Wallet", "fashion", 5, 9),
    ("Basic Drawstring Backpack", "fashion", 6, 11),
    ("Plastic Water Jug 5L", "kitchen", 6, 10),
    ("Bug Repellent Spray", "health", 5, 9),
    ("Foam Yoga Block", "fitness", 5, 9),
    ("Basic Jump Rope", "fitness", 4, 7),
    ("Resistance Band (Single)", "fitness", 4, 7),
    ("Cheap Flip Flops", "fashion", 4, 8),
    ("Pocket Notebook Pack (3)", "stationery", 4, 7),
    ("Small Desk Fan", "home", 8, 15),
    ("Basic Keychain Set", "accessories", 3, 6),
    ("Budget Lip Balm Pack (3)", "beauty", 3, 5),
    ("Cotton Pillow Cover (2)", "home", 7, 12),
    ("Laundry Detergent Sheets", "home", 5, 9),
    ("Craft Scissors", "tools", 3, 6),
    ("Disposable Rain Poncho", "lifestyle", 3, 6),
    ("Basic Nail Care Kit", "beauty", 4, 7),
    ("Simple Pill Organizer", "health", 3, 6),
    ("Cheap Garden Gloves", "garden", 3, 6),
    ("Paper Straw Pack (50)", "kitchen", 3, 5),
])

# ── LOW / MID ─────────────────────────────────────────────────────────────────
add("low", "mid", [
    ("Bluetooth Mini Speaker", "electronics", 18, 35),
    ("Canvas Sneakers", "fashion", 22, 42),
    ("Everyday Backpack", "fashion", 25, 48),
    ("Polarized Sunglasses", "fashion", 18, 32),
    ("Phone Ring Holder Stand", "accessories", 8, 15),
    ("Casual Cap", "fashion", 12, 22),
    ("Printed Hoodie", "fashion", 22, 42),
    ("Travel Neck Pillow", "travel", 14, 25),
    ("Portable Phone Charger 10000mAh", "electronics", 18, 32),
    ("Insulated Lunch Bag", "kitchen", 16, 28),
    ("Denim Jacket", "fashion", 32, 58),
    ("Sports Cap Pack (2)", "fashion", 12, 20),
    ("Wireless Mouse", "electronics", 16, 28),
    ("Artificial Desk Plant", "home", 14, 25),
    ("Casual Fabric Belt", "fashion", 14, 24),
    ("Basic Fitness Wristband", "electronics", 18, 32),
    ("Compact Travel Umbrella", "lifestyle", 12, 22),
    ("Stainless Steel Water Bottle", "lifestyle", 16, 28),
    ("Running Shorts", "fitness", 14, 25),
    ("Sports T-Shirt Pack (2)", "fashion", 18, 32),
    ("Adjustable Dumbbell 5kg", "fitness", 22, 40),
    ("Casual Slip-On Shoes", "fashion", 22, 40),
    ("Graphic Tee Pack (3)", "fashion", 18, 32),
    ("Small Shoulder Bag", "fashion", 22, 40),
    ("USB Hub 4-Port", "electronics", 12, 22),
    ("LED Desk Lamp", "home", 18, 32),
    ("Silicone Phone Wallet", "accessories", 8, 15),
    ("Cooling Sports Towel", "fitness", 10, 18),
    ("Basic Knee Support Brace", "health", 12, 22),
    ("Meal Prep Containers Set (4)", "kitchen", 16, 28),
    ("Folding Portable Table", "home", 28, 50),
    ("Casual Shorts Pack (2)", "fashion", 18, 32),
    ("Non-Slip Yoga Mat", "fitness", 18, 32),
    ("LED Digital Alarm Clock", "home", 12, 22),
    ("Simple 4-Cup Coffee Maker", "kitchen", 22, 38),
    ("Budget Electric Shaver", "health", 22, 38),
    ("Lightweight Rain Jacket", "lifestyle", 25, 45),
    ("Waterproof Fanny Pack", "fashion", 14, 25),
    ("Insulated Tumbler 500ml", "kitchen", 14, 25),
    ("Budget True Wireless Earbuds", "electronics", 22, 40),
    ("Dot Grid Notebook Journal", "stationery", 10, 18),
    ("Canvas Duffle Bag", "travel", 22, 40),
    ("Bike Lock Cable", "outdoor", 12, 22),
    ("Speed Skipping Rope Set", "fitness", 12, 22),
    ("Small Backpack 20L", "fashion", 22, 40),
    ("Basic Face Wash Kit", "beauty", 14, 25),
    ("Budget Hair Dryer", "beauty", 18, 35),
    ("Ceramic Plant Pot Set (3)", "garden", 14, 25),
    ("Floating Wall Shelf Set", "home", 18, 32),
    ("Car Phone Holder", "automotive", 10, 18),
    ("Phone Screen Protector Pack (2)", "accessories", 8, 15),
    ("Classic Chess Set", "lifestyle", 16, 28),
    ("Simple Wristwatch", "fashion", 22, 42),
    ("Reusable Coffee Cup Bamboo", "kitchen", 12, 22),
    ("Lightweight Sleeping Bag", "outdoor", 28, 50),
    ("Basic Camping Lantern", "outdoor", 14, 25),
    ("Collapsible Laundry Basket", "home", 14, 25),
    ("Budget Over-Ear Headphones", "electronics", 22, 40),
    ("2-Step Skincare Starter Set", "beauty", 16, 28),
    ("Training Gloves Pair", "fitness", 14, 25),
    ("Foam Roller 30cm", "fitness", 14, 25),
    ("Basic Drawing Tablet", "electronics", 25, 45),
    ("Academic Planner Journal", "stationery", 10, 18),
    ("High-Capacity Power Bank 20000mAh", "electronics", 22, 40),
    ("Budget Running Shoes", "fitness", 25, 45),
    ("Handheld Mini Fan USB", "lifestyle", 10, 18),
    ("Basic Electric Kettle", "kitchen", 16, 28),
    ("Portable Bluetooth Speaker Compact", "electronics", 22, 38),
    ("Casual Crossbody Bag", "fashion", 18, 32),
    ("Washable Microfiber Cloths Pack", "home", 8, 15),
    ("Stackable Storage Drawers", "home", 18, 32),
])

# ── LOW / HIGH ────────────────────────────────────────────────────────────────
add("low", "high", [
    ("Trendy Wireless Earbuds", "electronics", 38, 68),
    ("Budget Smartwatch", "electronics", 45, 85),
    ("Chunky Sneakers Trendy", "fashion", 42, 78),
    ("Graphic T-Shirts Set (3)", "fashion", 22, 40),
    ("Portable Bluetooth Speaker", "electronics", 28, 52),
    ("Ring Light 10-inch", "electronics", 28, 52),
    ("Phone Camera Lens Kit", "electronics", 25, 45),
    ("Streetwear Cap", "fashion", 20, 38),
    ("LED Strip Lights 5m", "home", 18, 35),
    ("Trendy Crossbody Bag", "fashion", 32, 58),
    ("Instant Print Camera", "electronics", 55, 95),
    ("Statement Sneakers Colorful", "fashion", 48, 88),
    ("Selfie Stick Tripod", "accessories", 16, 28),
    ("Retro Y2K Sunglasses", "fashion", 18, 32),
    ("Mini Keychain Speaker", "electronics", 14, 25),
    ("Trendy Phone Case Set (3)", "accessories", 18, 32),
    ("Pop Grip Bundle (3)", "accessories", 10, 18),
    ("Streetwear Beanie", "fashion", 16, 28),
    ("Aesthetic Desk Lamp LED", "home", 28, 52),
    ("Mini Neon Sign USB", "home", 22, 40),
    ("Holographic Backpack", "fashion", 28, 52),
    ("K-Beauty Starter Set", "beauty", 28, 52),
    ("Tie-Dye Hoodie Set", "fashion", 28, 52),
    ("Oversized Trendy Sunglasses", "fashion", 18, 32),
    ("Acrylic Nail Art Kit", "beauty", 22, 40),
    ("Polaroid Camera Film Pack (40)", "electronics", 18, 32),
    ("Fashionable Waist Bag", "fashion", 22, 40),
    ("Glitter & Marble Phone Case", "accessories", 10, 18),
    ("Retro Alarm Clock", "home", 18, 35),
    ("Boho Jewelry Set", "fashion", 18, 32),
    ("Photo Wall Grid Kit", "home", 18, 32),
    ("Aesthetic Plant Pot Set (3)", "garden", 16, 28),
    ("Budget Mini Projector", "electronics", 45, 85),
    ("Budget Gaming Headset", "electronics", 28, 52),
    ("Cute Stationery Set", "stationery", 12, 22),
    ("Vinyl Wall Decals Pack", "home", 12, 22),
    ("Trendy Casual Watch", "fashion", 28, 52),
    ("Floral Print Dress", "fashion", 28, 52),
    ("Aesthetic Printed Tote", "fashion", 14, 25),
    ("Book Light Rechargeable", "electronics", 10, 18),
    ("Scented Candle Set (3)", "home", 18, 32),
    ("Jade Face Roller Set", "beauty", 14, 25),
    ("Hair Accessories Set", "beauty", 14, 25),
    ("Charm Bracelet Set (3)", "fashion", 12, 22),
    ("Enamel Pin Collection (5)", "accessories", 10, 18),
    ("Illustrated Bullet Journal", "stationery", 14, 25),
    ("Reed Diffuser Set", "home", 16, 28),
    ("Magnetic Eyelash Kit", "beauty", 16, 28),
    ("Vintage-Style Sunglasses", "fashion", 18, 32),
    ("Patterned Socks Set (5)", "fashion", 14, 22),
    ("Graphic Crewneck Sweatshirt", "fashion", 28, 52),
    ("Changeable Letter Board", "home", 16, 28),
    ("Smart Fitness Band Budget", "electronics", 28, 52),
    ("Night Light Aesthetic Lamp", "home", 18, 32),
    ("Casual Platform Sneakers", "fashion", 32, 60),
    ("Hand-Woven Crochet Tote", "fashion", 22, 40),
    ("USB Mini Humidifier", "home", 14, 25),
    ("Cute Keychain Set (5)", "accessories", 10, 18),
    ("Waterproof Floating Speaker", "electronics", 28, 52),
    ("Adult Coloring Book Art Set", "lifestyle", 14, 25),
    ("Wireless Charging Pad Budget", "electronics", 16, 28),
    ("Glow-in-Dark Star Stickers", "home", 8, 15),
    ("Cap & Hat Set (2)", "fashion", 18, 32),
    ("Budget Hair Curler", "beauty", 22, 40),
    ("Crystal Hair Clips Set", "beauty", 10, 18),
    ("Canvas Art Print Set (2)", "home", 18, 32),
    ("Magnetic Bookmark Set", "stationery", 8, 14),
    ("UV Nail Lamp Kit", "beauty", 22, 40),
    ("Instant Photo Album", "lifestyle", 14, 25),
    ("Thermal Sticker Mini Printer", "electronics", 38, 68),
    ("Tumbler with Straw Lid", "kitchen", 16, 28),
])

# ── MID / LOW ─────────────────────────────────────────────────────────────────
add("mid", "low", [
    ("Fitness Tracker Band", "electronics", 38, 68),
    ("Premium Insulated Water Bottle", "lifestyle", 22, 40),
    ("Desk Organizer Set", "home", 25, 45),
    ("Premium Yoga Mat", "fitness", 28, 52),
    ("LED Reading Lamp", "home", 22, 40),
    ("Ergonomic Wireless Mouse", "electronics", 25, 45),
    ("Noise-Reducing Earplugs Premium", "lifestyle", 16, 28),
    ("Meal Prep Containers Set (6)", "kitchen", 20, 38),
    ("Compact Air Purifier", "home", 52, 95),
    ("Personal Blender", "kitchen", 32, 58),
    ("Premium Cotton Bedsheet Set", "home", 38, 68),
    ("Digital Kitchen Scale", "kitchen", 18, 32),
    ("Leather Weekly Planner", "stationery", 14, 25),
    ("Adjustable Laptop Stand", "electronics", 28, 52),
    ("Cast Iron Skillet", "kitchen", 32, 58),
    ("Reusable Grocery Bags Set (8)", "lifestyle", 14, 25),
    ("Tower Desk Fan", "home", 22, 40),
    ("36-Piece Basic Toolset", "tools", 28, 52),
    ("Smart Plug 4-Pack", "electronics", 22, 40),
    ("Bamboo Cutting Board Set (3)", "kitchen", 18, 32),
    ("Essential Oil Diffuser", "home", 22, 40),
    ("Electric Can Opener", "kitchen", 16, 28),
    ("6-Port USB Charger Hub", "electronics", 18, 32),
    ("Memory Foam Pillow", "home", 22, 40),
    ("Stainless Steel Pot Set (3)", "kitchen", 35, 65),
    ("Digital Blood Pressure Monitor", "health", 25, 45),
    ("Under-Desk Drawer Organizer", "home", 18, 32),
    ("Cordless Handheld Vacuum", "home", 35, 65),
    ("Digital Luggage Scale", "travel", 12, 22),
    ("Herb Garden Starter Kit", "garden", 18, 32),
    ("Resistance Training Set", "fitness", 22, 40),
    ("Wooden Minimalist Watch", "fashion", 32, 58),
    ("Leather Card Holder", "fashion", 18, 32),
    ("Multi-Level Shoe Rack", "home", 28, 52),
    ("Compact Dehumidifier", "home", 42, 78),
    ("Spice Rack Set (3-Tier)", "kitchen", 18, 32),
    ("Silicone Baking Mats Set (2)", "kitchen", 14, 25),
    ("Under-Bed Storage Boxes (2)", "home", 18, 32),
    ("Stainless Steel Thermos 1L", "kitchen", 18, 32),
    ("Electric Egg Cooker", "kitchen", 18, 32),
    ("Budget Cordless Drill", "tools", 42, 78),
    ("Bike Helmet Commuter", "fitness", 32, 58),
    ("Knee Brace Support", "health", 18, 32),
    ("Premium Sunscreen SPF50", "beauty", 12, 22),
    ("Leather Notebook Cover", "stationery", 18, 32),
    ("Wall-Mounted Key Holder", "home", 12, 22),
    ("Collapsible Silicone Bowls Set", "kitchen", 14, 25),
    ("Portable Folding Chair", "outdoor", 28, 52),
    ("Basic Camping Stove Burner", "outdoor", 22, 40),
    ("Car Seat Cushion", "automotive", 22, 40),
    ("Wrist Brace Support", "health", 14, 25),
    ("Smart Power Strip Timer", "electronics", 22, 40),
    ("Kitchen Peeler & Slicer Set", "kitchen", 12, 22),
    ("Wooden Book Stand", "stationery", 12, 22),
    ("Portable Tire Air Pump", "automotive", 25, 45),
    ("Stackable Drawer Organizer Set", "home", 18, 32),
    ("Whetstone Knife Sharpener Set", "kitchen", 18, 32),
    ("Heavy-Duty Deadbolt Lock", "home", 22, 40),
    ("Budget Indoor Security Camera", "electronics", 25, 45),
    ("Carbon Fiber Card Wallet", "fashion", 18, 32),
    ("Pour-Over Coffee Maker", "kitchen", 22, 40),
    ("UV Phone Sanitizer Box", "health", 18, 32),
    ("Budget Electric Toothbrush", "health", 22, 40),
    ("Non-Slip Bath Mat", "home", 14, 25),
    ("Bamboo Shelf Organizer", "home", 22, 40),
    ("Collapsible Dish Drying Rack", "kitchen", 18, 32),
    ("Digital Weather Station", "home", 22, 40),
    ("Hand Grip Strengthener Set", "fitness", 10, 18),
    ("Premium Resistance Bands Set (5)", "fitness", 18, 32),
    ("Foldable Step Stool", "home", 18, 32),
])

# ── MID / MID ─────────────────────────────────────────────────────────────────
add("mid", "mid", [
    ("Over-Ear Headphones", "electronics", 48, 88),
    ("Weekend Travel Duffel Bag", "fashion", 42, 78),
    ("Instant Camera with Film Pack", "electronics", 55, 95),
    ("Casual Analog Wristwatch", "fashion", 58, 105),
    ("Premium Board Game Set", "lifestyle", 28, 52),
    ("Mechanical Wireless Keyboard", "electronics", 35, 65),
    ("Compact Air Fryer 3L", "kitchen", 72, 130),
    ("Trail Running Shoes", "fitness", 55, 95),
    ("Insulated Backpack Cooler", "outdoor", 38, 68),
    ("Wi-Fi Digital Photo Frame", "electronics", 42, 78),
    ("Mini Portable Projector", "electronics", 88, 160),
    ("Standing Desk Converter", "home", 78, 140),
    ("Weighted Blanket 8kg", "home", 52, 95),
    ("Countertop Herb Garden Kit", "home", 38, 68),
    ("1000-Piece Premium Puzzle Set", "lifestyle", 22, 40),
    ("Premium Bike Helmet", "fitness", 35, 65),
    ("Camping Hammock with Straps", "outdoor", 38, 68),
    ("Rechargeable Electric Toothbrush", "health", 45, 82),
    ("Compact Countertop Microwave", "kitchen", 78, 140),
    ("Compact 1-Inch Sensor Camera", "electronics", 130, 230),
    ("Smart Bulbs Set (4-Pack)", "electronics", 28, 52),
    ("Compact Mechanical Keyboard", "electronics", 55, 95),
    ("Leather Loafers Casual", "fashion", 58, 105),
    ("Anti-Theft Laptop Backpack", "fashion", 42, 78),
    ("Portable SSD 1TB", "electronics", 65, 115),
    ("Smart Body Composition Scale", "health", 25, 45),
    ("Wireless Gaming Headset", "electronics", 55, 95),
    ("Electric Burr Coffee Grinder", "kitchen", 48, 88),
    ("Floating Wine Rack Wooden", "home", 28, 52),
    ("Yoga Block & Strap Set", "fitness", 18, 32),
    ("Multi-Tool Pocket Knife", "outdoor", 28, 52),
    ("Silicone Cooking Utensil Set (6)", "kitchen", 18, 32),
    ("RC Racing Car", "lifestyle", 42, 78),
    ("LEGO Architecture Set", "lifestyle", 48, 88),
    ("Wireless Charging Pad 15W", "electronics", 18, 32),
    ("Merino Wool Scarf", "fashion", 35, 65),
    ("Slim Leather Laptop Sleeve", "electronics", 28, 52),
    ("Portable Bluetooth Speaker Mid", "electronics", 35, 65),
    ("Vegetable Spiralizer Pro", "kitchen", 22, 40),
    ("6-Cup Rice Cooker", "kitchen", 35, 65),
    ("Bamboo Desk Organizer Set", "home", 22, 40),
    ("Stick Cordless Vacuum", "home", 78, 140),
    ("Folding Exercise Bike", "fitness", 120, 220),
    ("Adjustable Dumbbell Set 10kg Pair", "fitness", 48, 88),
    ("Smart Digital Door Lock", "home", 78, 140),
    ("Water Filter Pitcher", "kitchen", 28, 52),
    ("Solar String Lights 20m", "home", 22, 40),
    ("Ceramic Non-Stick Cookware Set", "kitchen", 65, 115),
    ("RFID Slim Leather Wallet", "fashion", 22, 40),
    ("Smart TV Stick 4K", "electronics", 35, 65),
    ("Portable 15-Inch Monitor", "electronics", 130, 230),
    ("Mini Espresso Maker", "kitchen", 55, 95),
    ("Polaroid-Style Instant Camera", "electronics", 55, 95),
    ("Hardcover Dotted Journal Set", "stationery", 18, 32),
    ("Fleece Sherpa Jacket", "fashion", 35, 65),
    ("Lightweight Trail Hiking Shoes", "fitness", 55, 95),
    ("Electric Pepper & Salt Grinder Set", "kitchen", 22, 40),
    ("3-in-1 Braided Cable Pack", "electronics", 12, 22),
    ("Solar Wireless Power Bank", "electronics", 28, 52),
    ("Mesh Ergonomic Office Chair Basic", "home", 88, 155),
    ("Bluetooth Turntable Record Player", "electronics", 78, 140),
    ("Electric Tabletop Grill", "kitchen", 48, 88),
    ("Wi-Fi Smart Security Camera", "electronics", 42, 78),
    ("3-Tier Rotating Spice Rack", "kitchen", 22, 40),
    ("Stretched Canvas Wall Art Set", "home", 28, 52),
    ("Stainless Steel Mixing Bowls Set", "kitchen", 28, 52),
    ("Electric Wine Opener", "kitchen", 22, 40),
    ("Travel Compression Bags Set", "travel", 18, 32),
    ("Yoga Wheel", "fitness", 22, 40),
    ("Smart Wi-Fi Plug 4-Pack", "electronics", 25, 45),
])

# ── MID / HIGH ────────────────────────────────────────────────────────────────
add("mid", "high", [
    ("Mid-Range Smartwatch GPS", "electronics", 120, 220),
    ("True Wireless ANC Earbuds", "electronics", 150, 280),
    ("Fashion Designer Sneakers", "fashion", 110, 200),
    ("Weekender Leather Travel Bag", "fashion", 75, 135),
    ("Bluetooth Bookshelf Speaker", "electronics", 90, 165),
    ("4K Action Camera", "electronics", 180, 330),
    ("Premium Gaming Headset", "electronics", 80, 145),
    ("GPS Drone Entry-Level", "electronics", 180, 330),
    ("Fashion Crossbody Bag", "fashion", 68, 125),
    ("Premium Yoga Mat Set with Bag", "fitness", 58, 105),
    ("Hydration Smart Water Bottle", "electronics", 52, 95),
    ("All-in-One Karaoke System", "electronics", 55, 100),
    ("Branded Acetate Sunglasses", "fashion", 85, 155),
    ("Mini Smart Refrigerator", "home", 95, 175),
    ("Multi-Device Wireless Charging Stand", "electronics", 28, 52),
    ("Sneaker Cleaning & Care Kit", "fashion", 22, 40),
    ("Premium Anti-Theft Backpack", "fashion", 100, 185),
    ("Smart Health Ring", "electronics", 150, 280),
    ("4K Waterproof Action Camera", "electronics", 200, 360),
    ("DualSense Controller & Stand Bundle", "electronics", 75, 135),
    ("Nintendo Switch Console", "electronics", 220, 400),
    ("Electric Longboard", "outdoor", 250, 450),
    ("Premium Inline Rollerblade Set", "fitness", 120, 220),
    ("5-Ply Stainless Steel Cookware Set", "kitchen", 120, 220),
    ("Cold Brew Coffee Maker Set", "kitchen", 42, 78),
    ("Vitamin & Supplement Bundle", "health", 52, 95),
    ("Premium Duffel Gym Bag", "fitness", 58, 105),
    ("Slim Business Laptop Bag", "fashion", 52, 95),
    ("Portable Karaoke Bluetooth Mic", "electronics", 55, 95),
    ("Smart Outdoor Pizza Oven", "kitchen", 220, 400),
    ("Hardshell Carry-On Luggage", "travel", 100, 185),
    ("ANC True Wireless Earphones", "electronics", 120, 220),
    ("Premium Over-Ear Wireless Headphones", "electronics", 130, 240),
    ("Smart Connected Jump Rope", "fitness", 48, 88),
    ("Robot Mop & Vacuum Combo", "home", 180, 330),
    ("Hiking Daypack 30L", "outdoor", 75, 135),
    ("Luxury Silk Pillowcase Set (2)", "home", 52, 95),
    ("Premium Curved LED Lamp", "home", 52, 95),
    ("Fashion GPS Smartwatch", "fashion", 130, 240),
    ("Smart WiFi Thermostat", "electronics", 120, 220),
    ("Shiatsu Electric Foot Massager", "health", 58, 105),
    ("Cordless Neck & Shoulder Massager", "health", 42, 78),
    ("Smart Air Fryer 5.5L", "kitchen", 120, 220),
    ("Sonic Electric Toothbrush", "health", 55, 100),
    ("Complete Beard Grooming Kit", "beauty", 42, 78),
    ("Multi-Step Premium Skincare Set", "beauty", 78, 140),
    ("Bifold Leather Wallet", "fashion", 45, 82),
    ("Polarized Sport Sunglasses", "fashion", 58, 105),
    ("Compact Mirrorless Camera", "electronics", 280, 510),
    ("Camera Accessories Bundle", "electronics", 65, 115),
    ("True Wireless Sports Earphones", "electronics", 75, 135),
    ("Smart Sunrise Alarm Clock", "electronics", 52, 95),
    ("Portable Power Station 500Wh", "electronics", 280, 510),
    ("Ergonomic Racing Gaming Chair", "home", 220, 400),
    ("Electric Heated Blanket", "home", 65, 115),
    ("Smart Indoor Herb Garden Kit", "garden", 75, 135),
    ("Premium Cocktail Making Set", "kitchen", 55, 95),
    ("Enameled Cast Iron Dutch Oven", "kitchen", 78, 140),
    ("Percussion Massage Gun", "health", 75, 135),
    ("Folding Electric Fat Tire Bike", "outdoor", 380, 680),
    ("Premium Inflatable Paddleboard Set", "outdoor", 300, 540),
    ("MIPS Cycling Helmet", "fitness", 100, 185),
    ("Personalized Leather Journal", "stationery", 28, 52),
    ("Instax Wide Instant Camera", "electronics", 95, 175),
    ("Portable Projector Screen 100-inch", "electronics", 55, 95),
    ("Modular Floating Shelf System", "home", 65, 115),
    ("Smart Automatic Pet Feeder", "pets", 75, 135),
    ("Designer Luxury Phone Case", "accessories", 55, 95),
    ("Carbon Fiber Phone Stand", "accessories", 22, 40),
    ("Premium Multi-Cooker 6L", "kitchen", 120, 220),
])

# ── HIGH / LOW ────────────────────────────────────────────────────────────────
add("high", "low", [
    ("Premium ANC Over-Ear Headphones", "electronics", 200, 380),
    ("Bean-to-Cup Coffee Machine", "kitchen", 180, 340),
    ("Full-Grain Leather Wallet", "fashion", 75, 135),
    ("Ergonomic Executive Office Chair", "home", 280, 510),
    ("Lacquer Fountain Pen Set", "stationery", 55, 95),
    ("1000TC Egyptian Cotton Bedding Set", "home", 140, 250),
    ("Crystal Wine Decanter & Glasses", "home", 55, 95),
    ("HEPA Smart Air Purifier Large", "home", 220, 400),
    ("Full-Grain Leather Desk Organizer", "home", 58, 105),
    ("Electric Height-Adjustable Desk", "home", 300, 540),
    ("8-Piece Professional Knife Set", "kitchen", 155, 280),
    ("Smart Learning Thermostat", "electronics", 110, 200),
    ("Premium Merino Wool Blanket", "home", 98, 180),
    ("Multi-Stage Water Purifier System", "kitchen", 185, 340),
    ("Pure Cashmere Scarf", "fashion", 85, 155),
    ("Full-Grain Leather Executive Briefcase", "fashion", 175, 320),
    ("Burr Coffee Grinder Pro", "kitchen", 135, 245),
    ("Ergonomic Lumbar Support Cushion", "home", 120, 220),
    ("Hardshell 3-Piece Luggage Set", "travel", 200, 360),
    ("Double-Wall Titanium Flask", "lifestyle", 48, 88),
    ("Premium Leather Passport Wallet", "travel", 42, 78),
    ("Superfine Merino Wool Crewneck", "fashion", 110, 200),
    ("Classic Polarized Sunglasses Premium", "fashion", 130, 240),
    ("Smart Door Lock with Video", "home", 180, 330),
    ("Dyson-Style Cordless Vacuum", "home", 280, 510),
    ("Commercial-Grade Blender", "kitchen", 220, 400),
    ("Cast Iron Reversible Griddle Grill", "kitchen", 68, 125),
    ("5-Camera Smart Home Security Bundle", "electronics", 280, 510),
    ("Premium 10-Inch Hybrid Mattress", "home", 400, 720),
    ("Premium Whey Protein 5lb Set", "health", 78, 140),
    ("Complete Home Yoga Equipment Set", "fitness", 78, 140),
    ("1000-Lumen Tactical Flashlight", "outdoor", 42, 78),
    ("4-Person Premium Camping Tent", "outdoor", 220, 400),
    ("Full-Grain Leather Messenger Bag", "fashion", 130, 240),
    ("Automatic Double Watch Winder", "fashion", 88, 160),
    ("Wireless Ergonomic Mouse Premium", "electronics", 55, 95),
    ("Solid Bamboo Bedroom Furniture Set", "home", 480, 880),
    ("10-Piece Hard-Anodized Cookware Set", "kitchen", 240, 440),
    ("Smart 10-inch Display Hub", "electronics", 130, 240),
    ("Handcrafted Marble Chess Set", "lifestyle", 98, 180),
    ("60-Pint Energy-Star Dehumidifier", "home", 185, 340),
    ("Chemex Pour-Over Coffee Set", "kitchen", 68, 125),
    ("Pure Cashmere Throw Blanket", "home", 120, 220),
    ("Lambskin Leather Driving Gloves", "fashion", 88, 160),
    ("Professional Cordless Hair Clipper", "beauty", 75, 135),
    ("6L Cool-Mist Ultrasonic Humidifier", "home", 88, 160),
    ("20-Piece Cordless Power Tool Set", "tools", 280, 510),
    ("Yoga Bolster & Meditation Set", "fitness", 55, 95),
    ("Immersion Circulator Sous Vide", "kitchen", 130, 240),
    ("Smart Indoor Garden 24-Pod System", "garden", 130, 240),
    ("Fingerprint Biometric Home Safe", "home", 120, 220),
    ("Ergonomic Kneeling Chair", "home", 180, 330),
    ("Solid Oak Coffee Table", "home", 380, 680),
    ("Premium Wireless Bookshelf Speakers", "electronics", 220, 400),
    ("Medical-Grade Posture Corrector", "health", 55, 95),
    ("Premium Whiskey Decanter Set", "lifestyle", 120, 220),
    ("Hand-Painted Fine Bone China Tea Set", "kitchen", 120, 220),
    ("Smart Wi-Fi Body Composition Scale", "health", 55, 95),
    ("Rechargeable Camping Lantern Pro", "outdoor", 48, 88),
    ("Full-Grain Leather Cardholder", "fashion", 55, 95),
    ("100% Mulberry Silk Robe", "fashion", 130, 240),
    ("Crystal Whiskey Decanter & Glasses", "lifestyle", 88, 160),
    ("Smart Wi-Fi Garage Door Opener", "home", 130, 240),
    ("Luxury Spa Home Gift Set", "beauty", 98, 180),
    ("Ebony Wood Watch Display Box", "fashion", 75, 135),
    ("Multi-Function Pressure Cooker 8L", "kitchen", 130, 240),
    ("Wireless White Noise Machine", "health", 48, 88),
    ("Heavy-Duty Wall-Mounted Pull-Up Bar", "fitness", 55, 95),
    ("IP66 Outdoor Bluetooth Speaker", "electronics", 130, 240),
    ("Wind-Resistant Carbon Fiber Umbrella", "lifestyle", 75, 135),
    ("Premium Golf Accessories Bundle", "sports", 75, 135),
])

# ── HIGH / MID ────────────────────────────────────────────────────────────────
add("high", "mid", [
    ("Smart Robot Vacuum Cleaner", "home", 320, 580),
    ("Semi-Pro Espresso Machine", "kitchen", 380, 680),
    ("Pebbled Leather Tote Bag", "fashion", 420, 750),
    ("Smart Home Hub Display", "electronics", 125, 225),
    ("Temperature-Control Smart Kettle", "kitchen", 95, 175),
    ("Smart HEPA Air Purifier Pro", "electronics", 200, 360),
    ("10-Piece Clad Stainless Cookware", "kitchen", 260, 480),
    ("Slim Bi-Fold Designer Wallet", "fashion", 160, 290),
    ("4K Smart Video Doorbell", "electronics", 140, 255),
    ("Sit-Stand Electric Desk 140cm", "home", 340, 620),
    ("Professional High-Speed Blender", "kitchen", 175, 320),
    ("Double-Faced Wool Overcoat", "fashion", 240, 440),
    ("Programmable Color LED Lighting Kit", "electronics", 110, 200),
    ("Full-Grain Leather Laptop Bag", "fashion", 185, 340),
    ("Premium Hybrid ANC Earbuds", "electronics", 220, 400),
    ("8-Camera AI Home Security System", "electronics", 260, 480),
    ("Professional Chef Knife Set", "kitchen", 200, 360),
    ("19mm Mulberry Silk Pillowcase Set (4)", "home", 100, 185),
    ("French Door Smart Refrigerator", "home", 1800, 3200),
    ("Full-Frame Mirrorless Camera", "electronics", 1800, 3200),
    ("Mid-Drive Electric Commuter Bike", "outdoor", 1200, 2200),
    ("AI-Powered Washing Machine", "home", 800, 1450),
    ("High-End Gaming Desktop PC", "electronics", 1200, 2200),
    ("32-Inch 4K UHD Designer Monitor", "electronics", 420, 750),
    ("Italian Leather Sectional Sofa", "home", 2200, 4000),
    ("Titanium Aviator Sunglasses", "fashion", 220, 400),
    ("Solid Hardwood Dining Table", "home", 900, 1600),
    ("1000TC Sateen Luxury Bedding Set", "home", 280, 510),
    ("24-Bottle Wine Cooler", "kitchen", 280, 510),
    ("Commercial-Grade Folding Treadmill", "fitness", 700, 1280),
    ("Zero-Gravity Massage Chair", "home", 900, 1600),
    ("Kamado Charcoal Smart Grill", "kitchen", 380, 680),
    ("Italian Leather Portfolio Briefcase", "fashion", 280, 510),
    ("Carbon Plate Marathon Shoes", "fitness", 160, 290),
    ("Commercial Spin Bike", "fitness", 500, 900),
    ("Aromatherapy Luxury Bath Set", "beauty", 120, 220),
    ("Rare Tea Selection Luxury Set", "kitchen", 140, 255),
    ("Hi-Fi Active Bookshelf Speakers Pair", "electronics", 320, 580),
    ("Luxury Scented Candle Set", "home", 120, 220),
    ("High-Density Feather Sofa Cushions (4)", "home", 140, 255),
    ("Goodyear-Welted Oxford Shoes", "fashion", 280, 510),
    ("Premium Handbag Organizer Set", "fashion", 75, 135),
    ("Microchip Smart Pet Door", "pets", 200, 360),
    ("Mid-Range GPS Mapping Drone", "electronics", 500, 900),
    ("Robot Lawn Mower 1000sqm", "garden", 700, 1280),
    ("Smart Solar Pool Heater", "outdoor", 320, 580),
    ("Professional Sous Vide Immersion Set", "kitchen", 130, 240),
    ("Professional Stand Mixer", "kitchen", 300, 540),
    ("Energy-Star Whole-Home Dehumidifier", "home", 380, 680),
    ("Laser Robot Vacuum & Mop Premium", "home", 500, 900),
    ("Engineered Hi-Fi Portable Speaker", "electronics", 280, 510),
    ("Premium Acetate Prescription Frame", "health", 200, 360),
    ("Cashmere Luxury Throw Blanket", "home", 240, 440),
    ("Hard-Shell Spinner Luggage Set (3pc)", "travel", 320, 580),
    ("Dolby Atmos Smart Home Theater", "electronics", 800, 1450),
    ("Cognac Leather Armchair", "home", 700, 1280),
    ("Power-Lift Premium Recliner", "home", 700, 1280),
    ("Planar Magnetic Gaming Headset", "electronics", 200, 360),
    ("Smart Countertop Convection Oven", "kitchen", 280, 510),
    ("Brushless Cordless Impact Driver Set", "tools", 200, 360),
    ("Suede Chelsea Boots", "fashion", 220, 400),
    ("Commercial Gym Half-Rack Bundle", "fitness", 600, 1100),
    ("Upholstered King Bedroom Set", "home", 1800, 3200),
    ("Dual-Zone Large Air Fryer Oven", "kitchen", 200, 360),
    ("Built-In Wi-Fi Dishwasher", "home", 600, 1100),
    ("4K Laser Smart Projector", "electronics", 600, 1100),
    ("Organic Pima Cotton Bathrobe Set (2)", "fashion", 180, 330),
    ("Motorized Smart Window Blind System", "home", 320, 580),
    ("Orthopedic Bolster Dog Bed XL", "pets", 120, 220),
    ("Tungsten Carbon Fiber Card Wallet", "fashion", 95, 175),
])

# ── HIGH / HIGH ───────────────────────────────────────────────────────────────
add("high", "high", [
    ("iPhone 15 Pro Max 1TB", "electronics", 1200, 1600),
    ("MacBook Pro 16-Inch M3 Max", "electronics", 2800, 4200),
    ("OLED 77-Inch 4K Smart TV", "electronics", 2000, 3800),
    ("Swiss Luxury Chronograph Watch", "fashion", 4500, 12000),
    ("Iconic Designer Leather Handbag", "fashion", 2200, 5500),
    ("Premium ANC Headphones Flagship", "electronics", 350, 620),
    ("High-End Gaming Laptop RTX 4090", "electronics", 2500, 4500),
    ("Oversized Luxury Designer Sunglasses", "fashion", 350, 750),
    ("Dolby Atmos Premium Home Theater", "electronics", 1800, 3500),
    ("Niche Luxury Perfume Collection", "beauty", 280, 600),
    ("Titanium Ceramic Smartwatch Premium", "electronics", 500, 900),
    ("Handcrafted Leather Oxford Shoes", "fashion", 500, 1100),
    ("Full-Frame Sensor Mirrorless Pro Camera", "electronics", 2800, 5500),
    ("Designer Lambskin Leather Jacket", "fashion", 1200, 2800),
    ("Carbon & Titanium Premium E-Bike", "outdoor", 3500, 7000),
    ("Reference-Grade Floorstanding Speakers", "electronics", 2200, 5500),
    ("Diamond & Sapphire Jewelry Set", "fashion", 3500, 12000),
    ("Bespoke Hard-Shell Luxury Luggage Set", "travel", 800, 1800),
    ("8K Mapping Cinematic Drone", "electronics", 1800, 3500),
    ("Premium Wellness & Recovery Spa Kit", "beauty", 350, 700),
    ("Samsung Galaxy S25 Ultra 1TB", "electronics", 1200, 1600),
    ("Limited-Edition Gaming Console Bundle", "electronics", 600, 1200),
    ("Loro Piana-Style Cashmere Overcoat", "fashion", 1800, 4500),
    ("Hand-Engraved Dress Watch", "fashion", 2800, 9000),
    ("Structured Monogram Leather Tote", "fashion", 1800, 4500),
    ("8K Laser Home Cinema Projector", "electronics", 3500, 8000),
    ("Built-In Smart Refrigerator Premium", "home", 2800, 5500),
    ("La Marzocco-Style Espresso Machine", "kitchen", 1200, 2800),
    ("Built-In Wine & Spirits Cellar", "kitchen", 2200, 5500),
    ("Self-Emptying Robot Vacuum Pro", "home", 800, 1600),
    ("Smart Home Full Bundle Pro", "electronics", 500, 1100),
    ("Level-2 Home EV Charger", "automotive", 600, 1200),
    ("18K Gold & Diamond Bracelet", "fashion", 1800, 6000),
    ("Pavé Diamond Drop Earrings", "fashion", 2200, 8000),
    ("Globe-Trotter-Style Luxury Luggage", "travel", 900, 2200),
    ("Cinema-Grade Photography Bundle", "electronics", 3500, 8000),
    ("Full-Grain Hand-Stitched Leather Sofa", "home", 4500, 9000),
    ("Frameless Glass Steam Shower System", "home", 2800, 6000),
    ("Luxury Smart Home Automation Bundle", "electronics", 3500, 8000),
    ("Ottoman King Platform Bed Frame", "home", 2200, 5500),
    ("Blade & Steel Premium Golf Club Set", "sports", 1200, 2800),
    ("Carbon Ski & Boot Bundle", "sports", 1200, 2800),
    ("Big Wave Surfboard", "sports", 800, 1800),
    ("Titanium-Frame Road Bicycle", "outdoor", 2800, 6500),
    ("Executive Wellness Retreat Package", "health", 1800, 4500),
    ("Full Kitchen Appliance Bundle Premium", "kitchen", 3500, 8000),
    ("Savant-Style Pro Smart Home System", "electronics", 4500, 12000),
    ("Freestanding Marble Clawfoot Bathtub", "home", 2800, 6500),
    ("Italian Marble Coffee Table", "home", 1200, 3200),
    ("4-Person Indoor Infrared Sauna", "home", 2800, 6500),
    ("Samsung 98-Inch MicroLED TV", "electronics", 4500, 12000),
    ("Signature Designer Belt", "fashion", 350, 750),
    ("Medium-Format Portrait Camera", "electronics", 5500, 12000),
    ("Hi-Fi Reference Turntable System", "electronics", 1200, 3200),
    ("Custom-Initials Business Class Luggage", "travel", 1200, 2800),
    ("Smart BBQ & Smoker System", "kitchen", 600, 1200),
    ("Luxury Silk & Linen Tie Collection", "fashion", 180, 380),
    ("Poltrona Frau-Style Executive Chair", "home", 2200, 5500),
    ("Limited Edition Signed Canvas Art", "home", 1200, 3500),
    ("InBody-Style High-Precision Health Scale", "health", 350, 700),
    ("Audeze LCD-Style Planar Headphones", "electronics", 800, 1800),
    ("La Cornue-Style Luxury Range", "kitchen", 4500, 12000),
    ("Oakworks-Style Professional Massage Table", "health", 1200, 3200),
    ("Hand-Woven Cashmere Throw Collection", "home", 600, 1600),
    ("TAG Heuer-Style Luxury Smartwatch", "electronics", 900, 2200),
    ("Goyard-Style Luxury Designer Backpack", "fashion", 1800, 4500),
    ("Annex Rooftop Tent Premium", "outdoor", 1200, 2800),
    ("Hand-Guilloché Chronograph Watch", "fashion", 3500, 9000),
    ("Zeiss-Grade Prime Lens Set", "electronics", 3500, 9000),
    ("Ajax-Style Smart Security System Pro", "electronics", 800, 1800),
    ("Polished Stainless Luxury Desk Clock", "home", 350, 750),
])


# ── Write CSV ─────────────────────────────────────────────────────────────────
fieldnames = ["product_id", "name", "category", "income_level", "spend_level", "price_range"]
with open("data/products.csv", "w", newline="", encoding="utf-8") as f:
    writer = csv.DictWriter(f, fieldnames=fieldnames)
    writer.writeheader()
    for i, p in enumerate(products, start=1):
        writer.writerow({
            "product_id": i,
            "name": p["name"],
            "category": p["category"],
            "income_level": p["income_level"],
            "spend_level": p["spend_level"],
            "price_range": p["price_range"],
        })

print(f"Generated {len(products)} products -> data/products.csv")

from collections import Counter
bucket_counts = Counter((p["income_level"], p["spend_level"]) for p in products)
for bucket, count in sorted(bucket_counts.items()):
    print(f"  {bucket[0]}/{bucket[1]}: {count} products")
