"""
persona_config.py
Auto-generated by train_model.py from the trained K-Means centroids.
Maps each cluster ID -> persona name, description, a display color,
and a normalized (x, y) position for the cluster map.
Product recommendations are NOT stored here -- see recommend.py,
which scores products from data/products.csv against the customer's
actual income/spending level using the thresholds below.
"""

INCOME_LOW_MAX = 32.4
INCOME_HIGH_MIN = 146.2
SPEND_LOW_MAX = 28.7
SPEND_HIGH_MIN = 68.3

PERSONA_MAP = {
    0: {
        "persona": 'Premium High-Spender',
        "description": 'High income and high spending on premium products.',
        "income_level": 'high',
        "spend_level": 'high',
        "color": '#FF6B6B',
        "centroid": {'x': 78.9, 'y': 10.0},
    },
    1: {
        "persona": 'Value-Focused Spender',
        "description": 'Limited income with moderate spending focused on selected purchases.',
        "income_level": 'low',
        "spend_level": 'mid',
        "color": '#4ECDC4',
        "centroid": {'x': 10.0, 'y': 49.2},
    },
    2: {
        "persona": 'Frugal High-Earner',
        "description": 'High income but cautious with spending; buys selectively.',
        "income_level": 'high',
        "spend_level": 'low',
        "color": '#FFD166',
        "centroid": {'x': 85.3, 'y': 88.7},
    },
    3: {
        "persona": 'Cautious Saver',
        "description": 'Comfortable income, but spends carefully.',
        "income_level": 'mid',
        "spend_level": 'low',
        "color": '#A78BFA',
        "centroid": {'x': 37.3, 'y': 89.7},
    },
    4: {
        "persona": 'Enthusiastic Spender',
        "description": 'Modest income, but spends enthusiastically and often.',
        "income_level": 'low',
        "spend_level": 'high',
        "color": '#06D6A0',
        "centroid": {'x': 10.3, 'y': 11.5},
    },
    5: {
        "persona": 'Steady High-Income Spender',
        "description": 'High income with steady, considered spending habits.',
        "income_level": 'high',
        "spend_level": 'mid',
        "color": '#F473B9',
        "centroid": {'x': 84.0, 'y': 49.7},
    },
    6: {
        "persona": 'Balanced Spender',
        "description": 'Moderate income and moderate spending; a balanced shopper.',
        "income_level": 'mid',
        "spend_level": 'mid',
        "color": '#4D96FF',
        "centroid": {'x': 37.6, 'y': 49.1},
    },
    7: {
        "persona": 'Budget-Conscious Customer',
        "description": 'Low income and low spending, with a preference for keeping purchases within a budget.',
        "income_level": 'low',
        "spend_level": 'low',
        "color": '#FFA94D',
        "centroid": {'x': 10.1, 'y': 90.0},
    },
    8: {
        "persona": 'Active Spender',
        "description": 'Comfortable income and enjoys spending freely.',
        "income_level": 'mid',
        "spend_level": 'high',
        "color": '#82C91E',
        "centroid": {'x': 38.0, 'y': 11.5},
    },
    9: {
        "persona": 'Premium High-Spender #2',
        "description": 'High income and high spending on premium products.',
        "income_level": 'high',
        "spend_level": 'high',
        "color": '#E599F7',
        "centroid": {'x': 90.0, 'y': 14.4},
    },
}
